CREATE TABLE orders
(
  id INT NOT NULL AUTO_INCREMENT,
  date_posted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  part_number VARCHAR(30) NOT NULL,
  address VARCHAR(250) NOT NULL,
  quantity SMALLINT NOT NULL DEFAULT 0,
  fulfilled BOOLEAN NOT NULL,
  PRIMARY KEY (id)
);